"""change model column to bike_model

Revision ID: 1b34caa15343
Revises: b0a74a6fc284
Create Date: 2017-08-18 18:33:59.880954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b34caa15343'
down_revision = 'b0a74a6fc284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('bike_model', sa.String(length=80), nullable=True))
    op.drop_column('bike', 'model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('bike', 'bike_model')
    # ### end Alembic commands ###
