"""change customer-transaction lazy from dynamic to select

Revision ID: b0a74a6fc284
Revises: c22fefad3bd6
Create Date: 2017-08-18 17:55:38.614671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a74a6fc284'
down_revision = 'c22fefad3bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
