"""test

Revision ID: c22fefad3bd6
Revises: b2a17cacdb0c
Create Date: 2017-08-18 17:48:49.509158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22fefad3bd6'
down_revision = 'b2a17cacdb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INPATIENT', 'MERCH', 'OUTPATIENT', name='transactiontype'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TransactionBike',
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], )
    )
    op.create_table('TransactionItem',
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], )
    )
    op.create_table('TransactionRepair',
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('repair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repair.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TransactionRepair')
    op.drop_table('TransactionItem')
    op.drop_table('TransactionBike')
    op.drop_table('transaction')
    op.drop_table('bike')
    op.drop_table('user')
    op.drop_table('repair')
    op.drop_table('item')
    op.drop_table('customer')
    # ### end Alembic commands ###
